export default {
    products: [
      {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/dress2.jpg',
        price: 60,
        brand: ' Nike',
        rating: 3,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock: 3,
      },
      {
        _id: '3',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/d2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 2,
        numReviews: 8,
        countInStock:0,
      }, {
        _id: '4',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/p2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 5,
        numReviews: 8,
        countInStock: 16,
      },
      {
        _id: '5',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/dress3.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 50,
        brand: ' Nike',
        rating: 2,
        numReviews: 5,
        countInStock: 3,
      },
      {
        _id: '7',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock: 3,
      },
      {
        _id: '8',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/men3.jpeg',
        price: 50,
        brand: ' Nike',
        rating: 3,
        numReviews: 5,
        countInStock: 3,
      },
      {
        _id: '9',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/d2.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock: 3,
      },
      {
        _id: '10',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 50,
        brand: ' Nike',
        rating: 5,
        numReviews: 5,
        countInStock: 3,
      }
    ]
  }